name: Clear Recent Messages

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  delete_recent_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run delete_recent_messages script
        env:
          BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python testing/clear_messages_telegram.py
